function timeTravelBack (location_x: number, location_y: number) {
    tiles.loadMap(tilemap3)
    mySprite.setImage(img`
        ..........fffffff.............
        .........fdddddddf............
        ........fdddddddddf...........
        .......fddfdddddfddf..........
        .......fdddddddddddf..........
        .......fdddddddddddf..........
        .......fdddddddddddf..........
        .......fddfffffffddf..........
        .......fdddddddddddf..........
        .......fdddddddddddf..........
        ........fdddddddddf...........
        .........fdddddddf............
        ..........fffffff.............
        .............f................
        .............f................
        .............f................
        .............f................
        .............f................
        ......ff.....f.....ff.........
        ......fffffffffffffff.........
        ......ff.....f.....ff.........
        .............f................
        .............f................
        .............f................
        .............f................
        ...........fffff..............
        ...........f...f..............
        ...........f...f..............
        ..........fff.fff.............
        ..........fff.fff.............
        `)
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (currentPlayerIsOld == true) {
        timeTravelBack(mySprite.x, mySprite.y)
    } else {
    	
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        mySprite.vy += -100
    }
})
scene.onOverlapTile(SpriteKind.Player, tiles.util.door0, function (sprite, location) {
    tiles.loadConnectedMap(ConnectionKind.Door1)
    tiles.placeOnRandomTile(mySprite, tiles.util.door1)
    scene.cameraFollowSprite(mySprite)
})
let currentPlayerIsOld = false
let tilemap3: tiles.WorldMap = null
let mySprite: Sprite = null
mySprite = sprites.create(img`
    .......................f......f.f...............................
    ........................f....f...f..............................
    ........................f...f....f..............................
    ........................f...f....f..............................
    .........................fffffffff..............................
    ........................fdddddddddf.............................
    .......................fdddddddddddf............................
    ......................fdddddddddddddf...........................
    .....................fdfffdddddddfffdf..........................
    .....................fdfffdddddddfffdf..........................
    .....................fdfffdddddddfffdf..........................
    .....................fdddddddddddddddf..........................
    .....................fdddddddddddddddf..........................
    .....................fddddddddddddfddf..........................
    .....................fddfdddddddddfddf..........................
    .....................fdddfdddddddffddf..........................
    .....................fdddfdddddddfdddf..........................
    ......................fdddfddddfffddf...........................
    .......................fdddfffffdddf............................
    ........................fdddddddddf.............................
    .........................fffffffff..............................
    ...........................fdddf................................
    ...........................fdddf................................
    ...........................fdddf................................
    ....................ffffffffffffffffffff........................
    ......fffff.........f777777777777777777f...........fffff........
    ......fdddfffffffffff777777777777777777fffffffffffffdddf........
    ......fdddffddddddddf777777777777777777fddddddddddffdddf........
    ......fdddfffffffffff777777777777777777fffffffffffffdddf........
    ......fffff.........f777777777777777777f...........fffff........
    ....................ffffffff777777ffffff........................
    ...........................f777777f.............................
    ...........................f777777f.............................
    ...........................f777777f.............................
    ...........................f777777f.............................
    ...........................f777777f.............................
    ...........................f777777f.............................
    ...........................f777777f.............................
    ...........................f777777f.............................
    ...........................ffffffff.............................
    ...........................faafaaaf.............................
    ...........................faafaaaf.............................
    ..........................faaf.faaf.............................
    ........................ffaaf..faaaf............................
    .......................faaaf...faaaaf...........................
    ......................faaaf.....faaaf...........................
    .......................fff.......fafdf..........................
    .......................fdf........ffddf.........................
    ......................fddf..........fdf.........................
    .....................fddf...........fddf........................
    ...................ffddf.............fddf.......................
    ..................fddff...............fdf.......................
    .................fddf.................fddf......................
    ..............ffffff...................fddf.....................
    ..............fdddf.....................ffffff..................
    ..............fdddf......................fdddf..................
    ..............fdddf......................fdddf..................
    ..............fffff......................fdddf..................
    .........................................fffff..................
    ................................................................
    ................................................................
    ................................................................
    ................................................................
    ................................................................
    `, SpriteKind.Player)
let tilemap1 = tiles.createMap(tilemap`level1`)
let tilemap2 = tiles.createMap(tilemap`level2`)
tilemap3 = tiles.createMap(tilemap`level16`)
tiles.loadMap(tilemap1)
mySprite.ay = 200
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite, 100, 0)
tiles.placeOnRandomTile(mySprite, assets.tile`myTile3`)
currentPlayerIsOld = true
tiles.coverAllTiles(assets.tile`myTile2`, assets.tile`myTile`)
tiles.coverAllTiles(assets.tile`myTile3`, assets.tile`myTile`)
tiles.coverAllTiles(tiles.util.door0, assets.tile`myTile1`)
tiles.coverAllTiles(tiles.util.door4, assets.tile`myTile0`)
tiles.connectMapById(tilemap1, tilemap2, ConnectionKind.Door1)
